/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.AlunoControle;
import java.awt.Toolkit;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.AlunoBEAN;
import modelo.CursoBEAN;

/**
 *
 * @author user
 */
public class JFRMCadastrarAluno extends javax.swing.JFrame {

    AlunoControle aluControl = new AlunoControle();
    /**
     * Creates new form JFRMCadastrarCursos
     */
    public JFRMCadastrarAluno() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        RBTNNao01.setSelected(true);
        RBTNNao02.setSelected(true);
        preencherCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        BGConhecinmentoEmInformatica = new javax.swing.ButtonGroup();
        BGPossuiCarteiraDeHabilitacao = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        lblName7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblName6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFAnoPeriodo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFTurma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFMatricula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TFOrgaoEmissor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CBEstadoCivil = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        FTFDataDeNascimento = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        TFRepresentanteLegal = new javax.swing.JTextField();
        TFEndereco = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TFEstado = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TFCidade = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        FTFCEP = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        FTFTelefone = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        FTFCelular = new javax.swing.JFormattedTextField();
        FTFCPF = new javax.swing.JFormattedTextField();
        TFRG = new javax.swing.JTextField();
        TFEmail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        RBTNSim01 = new javax.swing.JRadioButton();
        RBTNNao01 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        RBTNNao02 = new javax.swing.JRadioButton();
        RBTNSim02 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        FTFInicioDoCurso = new javax.swing.JFormattedTextField();
        FTFTerminoDoCurso = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        BTNCadastrar = new javax.swing.JButton();
        BTNLimpar = new javax.swing.JButton();
        CBCurso = new javax.swing.JComboBox<>();
        BTNVoltar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        JMICadastrar = new javax.swing.JMenuItem();
        JMILimpar = new javax.swing.JMenuItem();
        JMIVoltar = new javax.swing.JMenuItem();

        jLabel4.setText("Curso:");

        jLabel6.setText("Ano / Período:");

        jLabel9.setText("Matrícula:");

        jLabel16.setText("CPF:");

        jLabel18.setText("Endereço:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stagium - Cadastrar Aluno");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 255, 102));

        lblName.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        lblName.setText("T");

        lblName1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        lblName1.setText("G");

        lblName2.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        lblName2.setText("S");

        lblName3.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        lblName3.setText("A");

        lblName4.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        lblName4.setText("U");

        lblName5.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        lblName5.setText("M");

        lblName7.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        lblName7.setText("I");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblName5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName2)
                .addGap(1, 1, 1)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName5)
                .addGap(91, 91, 91)
                .addComponent(jLabel19))
        );

        lblName6.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        lblName6.setText("Cadastrar Aluno");

        jLabel2.setText("Nome do Aluno:");

        jLabel3.setText("Curso:");

        jLabel5.setText("Ano / Período:");

        jLabel7.setText("Turma:");

        jLabel8.setText("Matrícula:");

        jLabel10.setText("CPF:");

        jLabel11.setText("RG:");

        jLabel12.setText("Orgão Emissor:");

        jLabel13.setText("Estado Civil:");

        CBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro (a)", "Casado (a)", "Separado (a)", "Divorciado (a)", "Viúvo (a)" }));

        jLabel14.setText("Data de Nascimento");

        try {
            FTFDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setText("Rep. Legal:");

        TFRepresentanteLegal.setToolTipText("Representante legal caso o aluno seja menor de idade.");

        jLabel17.setText("Endereço:");

        TFEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEstadoActionPerformed(evt);
            }
        });

        jLabel20.setText("Estado:");

        TFCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFCidadeActionPerformed(evt);
            }
        });

        jLabel21.setText("Cidade:");

        jLabel22.setText("CEP:");

        try {
            FTFCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel23.setText("Telefone:");

        try {
            FTFTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel24.setText("Celular:");

        try {
            FTFCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            FTFCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFEmailActionPerformed(evt);
            }
        });

        jLabel25.setText("E-mail:");

        jLabel26.setText("Possui Conhecimento em Informática?");

        BGConhecinmentoEmInformatica.add(RBTNSim01);
        RBTNSim01.setText("Sim");

        BGConhecinmentoEmInformatica.add(RBTNNao01);
        RBTNNao01.setText("Não");

        jLabel27.setText("Possui Carteira de Habilitação?");

        BGPossuiCarteiraDeHabilitacao.add(RBTNNao02);
        RBTNNao02.setText("Não");

        BGPossuiCarteiraDeHabilitacao.add(RBTNSim02);
        RBTNSim02.setText("Sim");

        jLabel28.setText("Início do Curso:");

        jLabel29.setText("Formatura:");

        try {
            FTFInicioDoCurso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            FTFTerminoDoCurso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BTNCadastrar.setText("Cadastrar");
        BTNCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCadastrarActionPerformed(evt);
            }
        });

        BTNLimpar.setText("Limpar");
        BTNLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(BTNCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addComponent(BTNLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(BTNLimpar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblName6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(208, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FTFDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 173, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFEmail)
                                    .addComponent(TFCidade)
                                    .addComponent(TFEstado)
                                    .addComponent(TFEndereco)
                                    .addComponent(TFRepresentanteLegal)
                                    .addComponent(TFOrgaoEmissor)
                                    .addComponent(TFMatricula)
                                    .addComponent(TFTurma)
                                    .addComponent(TFAnoPeriodo)
                                    .addComponent(CBEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(FTFCEP)
                                    .addComponent(FTFTelefone)
                                    .addComponent(FTFCelular)
                                    .addComponent(FTFCPF)
                                    .addComponent(TFRG)
                                    .addComponent(TFNome)
                                    .addComponent(CBCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(RBTNSim02)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RBTNNao02))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(RBTNSim01)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(RBTNNao01))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FTFTerminoDoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FTFInicioDoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblName6)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RBTNSim01)
                    .addComponent(RBTNNao01)
                    .addComponent(CBCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFAnoPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TFTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBTNSim02)
                    .addComponent(RBTNNao02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(FTFInicioDoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(FTFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(FTFTerminoDoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TFRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TFOrgaoEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(CBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FTFDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TFRepresentanteLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(TFEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(FTFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(FTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(FTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(TFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        TFRepresentanteLegal.getAccessibleContext().setAccessibleName("");
        TFRepresentanteLegal.getAccessibleContext().setAccessibleDescription("");

        BTNVoltar.setText("Voltar");
        BTNVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenu.setText("Ações");

        JMICadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        JMICadastrar.setText("Cadastrar");
        JMICadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMICadastrarActionPerformed(evt);
            }
        });
        jMenu.add(JMICadastrar);

        JMILimpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        JMILimpar.setText("Limpar");
        JMILimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMILimparActionPerformed(evt);
            }
        });
        jMenu.add(JMILimpar);

        JMIVoltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        JMIVoltar.setText("Voltar");
        JMIVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIVoltarActionPerformed(evt);
            }
        });
        jMenu.add(JMIVoltar);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEmailActionPerformed

    private void TFCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFCidadeActionPerformed

    private void TFEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFEstadoActionPerformed

    private void JMIVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMIVoltarActionPerformed

    private void BTNVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BTNVoltarActionPerformed

    private void BTNCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCadastrarActionPerformed
        
                
        AlunoBEAN alu = new AlunoBEAN();
        
        String conhInfo = this.buttonGroupSelect();
        String cartHab = this.buttonGroup2Select();
        
        int codCurso = aluControl.codigoCurso((String) CBCurso.getSelectedItem());
        
        alu.setNome(TFNome.getText());
        alu.setCurCodigo(codCurso);
        alu.setAno_Periodo(TFAnoPeriodo.getText());
        alu.setTurma(TFTurma.getText());
        alu.setMatricula(TFMatricula.getText());
        alu.setCpf(FTFCPF.getText());
        alu.setRg(TFRG.getText());
        alu.setOrgEmissor(TFOrgaoEmissor.getText());
        alu.setEstadoCivil((String) CBEstadoCivil.getSelectedItem());
        alu.setDataNascimento(FTFDataDeNascimento.getText());
        alu.setRepresentanteLegal(TFRepresentanteLegal.getText());
        alu.setEndereco(TFEndereco.getText());
        alu.setEstado(TFEstado.getText());
        alu.setCidade(TFCidade.getText());
        alu.setCep(FTFCEP.getText());
        alu.setFone(FTFTelefone.getText());
        alu.setCelular(FTFCelular.getText());
        alu.setEmail(TFEmail.getText());
        alu.setConhecimento_informatica(conhInfo);
        alu.setCarteira_habilitacao(cartHab);
        alu.setInicioDoCurso(FTFInicioDoCurso.getText());
        alu.setFormatura(FTFTerminoDoCurso.getText());
        
        boolean r = aluControl.cadastrar(alu);

            if (r == true) {
                JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso!!!");
            } else if (r == false) {
                JOptionPane.showMessageDialog(null, "Erro ao Cadastrar: Aluno já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao Cadastrar!!!");
            }
    }//GEN-LAST:event_BTNCadastrarActionPerformed

    private void JMICadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMICadastrarActionPerformed
        AlunoBEAN alu = new AlunoBEAN();
        
        String conhInfo = this.buttonGroupSelect();
        String cartHab = this.buttonGroup2Select();
        
        int codCurso = aluControl.codigoCurso((String) CBCurso.getSelectedItem());
        
        alu.setNome(TFNome.getText());
        alu.setCurCodigo(codCurso);
        alu.setAno_Periodo(TFAnoPeriodo.getText());
        alu.setTurma(TFTurma.getText());
        alu.setMatricula(TFMatricula.getText());
        alu.setCpf(FTFCPF.getText());
        alu.setRg(TFRG.getText());
        alu.setOrgEmissor(TFOrgaoEmissor.getText());
        alu.setEstadoCivil((String) CBEstadoCivil.getSelectedItem());
        alu.setDataNascimento(FTFDataDeNascimento.getText());
        alu.setRepresentanteLegal(TFRepresentanteLegal.getText());
        alu.setEndereco(TFEndereco.getText());
        alu.setEstado(TFEstado.getText());
        alu.setCidade(TFCidade.getText());
        alu.setCep(FTFCEP.getText());
        alu.setFone(FTFTelefone.getText());
        alu.setCelular(FTFCelular.getText());
        alu.setEmail(TFEmail.getText());
        alu.setConhecimento_informatica(conhInfo);
        alu.setCarteira_habilitacao(cartHab);
        alu.setInicioDoCurso(FTFInicioDoCurso.getText());
        alu.setFormatura(FTFTerminoDoCurso.getText());
        
        boolean r = aluControl.cadastrar(alu);

            if (r == true) {
                JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso!!!");
            } else if (r == false) {
                JOptionPane.showMessageDialog(null, "Erro ao Cadastrar: Aluno já cadastrado");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao Cadastrar!!!");
            }
    }//GEN-LAST:event_JMICadastrarActionPerformed

    private void BTNLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimparActionPerformed
        TFNome.setText("");
        TFAnoPeriodo.setText("");
        TFTurma.setText("");
        TFMatricula.setText("");
        FTFCPF.setText("");
        TFRG.setText("");
        TFOrgaoEmissor.setText("");
        CBEstadoCivil.setSelectedIndex(0);
        FTFDataDeNascimento.setText("");
        TFRepresentanteLegal.setText("");
        TFEndereco.setText("");
        TFEstado.setText("");
        TFCidade.setText("");
        FTFCEP.setText("");
        FTFTelefone.setText("");
        FTFCelular.setText("");
        TFEmail.setText("");
        FTFInicioDoCurso.setText("");
        FTFTerminoDoCurso.setText("");
    }//GEN-LAST:event_BTNLimparActionPerformed

    private void JMILimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMILimparActionPerformed
        TFNome.setText("");
        TFAnoPeriodo.setText("");
        TFTurma.setText("");
        TFMatricula.setText("");
        FTFCPF.setText("");
        TFRG.setText("");
        TFOrgaoEmissor.setText("");
        CBEstadoCivil.setSelectedIndex(0);
        FTFDataDeNascimento.setText("");
        TFRepresentanteLegal.setText("");
        TFEndereco.setText("");
        TFEstado.setText("");
        TFCidade.setText("");
        FTFCEP.setText("");
        FTFTelefone.setText("");
        FTFCelular.setText("");
        TFEmail.setText("");
        FTFInicioDoCurso.setText("");
        FTFTerminoDoCurso.setText("");
    }//GEN-LAST:event_JMILimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRMCadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRMCadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRMCadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRMCadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRMCadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGConhecinmentoEmInformatica;
    private javax.swing.ButtonGroup BGPossuiCarteiraDeHabilitacao;
    private javax.swing.JButton BTNCadastrar;
    private javax.swing.JButton BTNLimpar;
    private javax.swing.JButton BTNVoltar;
    private javax.swing.JComboBox<String> CBCurso;
    private javax.swing.JComboBox<String> CBEstadoCivil;
    private javax.swing.JFormattedTextField FTFCEP;
    private javax.swing.JFormattedTextField FTFCPF;
    private javax.swing.JFormattedTextField FTFCelular;
    private javax.swing.JFormattedTextField FTFDataDeNascimento;
    private javax.swing.JFormattedTextField FTFInicioDoCurso;
    private javax.swing.JFormattedTextField FTFTelefone;
    private javax.swing.JFormattedTextField FTFTerminoDoCurso;
    private javax.swing.JMenuItem JMICadastrar;
    private javax.swing.JMenuItem JMILimpar;
    private javax.swing.JMenuItem JMIVoltar;
    private javax.swing.JRadioButton RBTNNao01;
    private javax.swing.JRadioButton RBTNNao02;
    private javax.swing.JRadioButton RBTNSim01;
    private javax.swing.JRadioButton RBTNSim02;
    private javax.swing.JTextField TFAnoPeriodo;
    private javax.swing.JTextField TFCidade;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFEndereco;
    private javax.swing.JTextField TFEstado;
    private javax.swing.JTextField TFMatricula;
    private javax.swing.JTextField TFNome;
    private javax.swing.JTextField TFOrgaoEmissor;
    private javax.swing.JTextField TFRG;
    private javax.swing.JTextField TFRepresentanteLegal;
    private javax.swing.JTextField TFTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    // End of variables declaration//GEN-END:variables

    private void preencherCombo() {
        ArrayList<CursoBEAN> cursos = aluControl.todosCursos();

        for (CursoBEAN curso : cursos) {
            CBCurso.addItem(curso.getNome());
        }
    }

    private String buttonGroupSelect() {
        RBTNSim01.setActionCommand("Sim");
        RBTNNao01.setActionCommand("Não");
        
        String select = BGConhecinmentoEmInformatica.getSelection().getActionCommand();
        
        return select;
    }

    private String buttonGroup2Select() {
        RBTNSim02.setActionCommand("Sim");
        RBTNNao02.setActionCommand("Não");
        
        String select = BGPossuiCarteiraDeHabilitacao.getSelection().getActionCommand();
        
        return select;
    }
}
