/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author user
 */
public class JFRMPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFRMPrincipal
     */
    public JFRMPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblName16 = new javax.swing.JLabel();
        lblName17 = new javax.swing.JLabel();
        lblName18 = new javax.swing.JLabel();
        lblName19 = new javax.swing.JLabel();
        lblName20 = new javax.swing.JLabel();
        lblName21 = new javax.swing.JLabel();
        lblName22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCadAluno = new javax.swing.JButton();
        btnCadEmpresa = new javax.swing.JButton();
        btnCadOrientador = new javax.swing.JButton();
        btnListAlunos = new javax.swing.JButton();
        btnListOrientadores = new javax.swing.JButton();
        btnListEmpresas = new javax.swing.JButton();
        lblName23 = new javax.swing.JLabel();
        lblName24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCadEstagio = new javax.swing.JButton();
        btnListEstagios = new javax.swing.JButton();
        btnCadCursos = new javax.swing.JButton();
        btnListCursos = new javax.swing.JButton();
        btnCadRepresentante = new javax.swing.JButton();
        btnListRepresentantes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadAluno = new javax.swing.JMenuItem();
        miCadOrientador = new javax.swing.JMenuItem();
        miCadEmpresa = new javax.swing.JMenuItem();
        miCadEstagio = new javax.swing.JMenuItem();
        miCadCurso = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miListAlunos = new javax.swing.JMenuItem();
        miListOrientadores = new javax.swing.JMenuItem();
        miListEmpresas = new javax.swing.JMenuItem();
        miListEstagios = new javax.swing.JMenuItem();
        miListCursos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jButton11.setText("jButton11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stagium - Principal");
        setMinimumSize(new java.awt.Dimension(867, 500));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jPanel4.setBackground(new java.awt.Color(0, 255, 102));

        lblName16.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        lblName16.setText("S");

        lblName17.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        lblName17.setText("T");

        lblName18.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        lblName18.setText("A");

        lblName19.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        lblName19.setText("G");

        lblName20.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        lblName20.setText("I");

        lblName21.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        lblName21.setText("U");

        lblName22.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        lblName22.setText("M");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblName20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        btnCadAluno.setText("Cadastrar Aluno");
        btnCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAlunoActionPerformed(evt);
            }
        });

        btnCadEmpresa.setText("Cadastrar Empresa");
        btnCadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEmpresaActionPerformed(evt);
            }
        });

        btnCadOrientador.setText("Cadastrar Orientador");
        btnCadOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadOrientadorActionPerformed(evt);
            }
        });

        btnListAlunos.setText("Listar Alunos");
        btnListAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAlunosActionPerformed(evt);
            }
        });

        btnListOrientadores.setText("Listar Orientadores");
        btnListOrientadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListOrientadoresActionPerformed(evt);
            }
        });

        btnListEmpresas.setText("Listar Empresas");
        btnListEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListEmpresasActionPerformed(evt);
            }
        });

        lblName23.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        lblName23.setText("Listar");

        lblName24.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        lblName24.setText("Cadastrar");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCadEstagio.setText("Cadastrar Estágio");
        btnCadEstagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadEstagioActionPerformed(evt);
            }
        });

        btnListEstagios.setText("Listar Estágios");
        btnListEstagios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListEstagiosActionPerformed(evt);
            }
        });

        btnCadCursos.setText("Cadastrar Cursos");
        btnCadCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCursosActionPerformed(evt);
            }
        });

        btnListCursos.setText("Listar Cursos");
        btnListCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCursosActionPerformed(evt);
            }
        });

        btnCadRepresentante.setText("Cadastrar Representante");
        btnCadRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRepresentanteActionPerformed(evt);
            }
        });

        btnListRepresentantes.setText("Listar Representantes");
        btnListRepresentantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListRepresentantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadRepresentante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadOrientador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblName24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnCadAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadEstagio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(215, 215, 215)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListEmpresas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListOrientadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblName23, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnListEstagios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListRepresentantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName23)
                    .addComponent(lblName24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListAlunos)
                    .addComponent(btnCadAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadOrientador)
                    .addComponent(btnListOrientadores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadEstagio)
                    .addComponent(btnListEstagios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListCursos)
                    .addComponent(btnCadCursos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadRepresentante)
                    .addComponent(btnListRepresentantes))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        btnSair.setText("Sair");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSair))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(btnSair)
                .addContainerGap())
        );

        jMenu1.setText("Cadastrar");

        miCadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        miCadAluno.setText("Cadastrar Aluno");
        miCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(miCadAluno);

        miCadOrientador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miCadOrientador.setText("Cadastrar Orientador");
        miCadOrientador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadOrientadorActionPerformed(evt);
            }
        });
        jMenu1.add(miCadOrientador);

        miCadEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        miCadEmpresa.setText("Cadastrar  Empresa");
        miCadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadEmpresa);

        miCadEstagio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        miCadEstagio.setText("Cadastrar Estágio");
        miCadEstagio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadEstagioActionPerformed(evt);
            }
        });
        jMenu1.add(miCadEstagio);

        miCadCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        miCadCurso.setText("Cadastrar Curso");
        miCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadCursoActionPerformed(evt);
            }
        });
        jMenu1.add(miCadCurso);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Listar");

        miListAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miListAlunos.setText("Listar Alunos");
        jMenu2.add(miListAlunos);

        miListOrientadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        miListOrientadores.setText("Listar Orientadores");
        jMenu2.add(miListOrientadores);

        miListEmpresas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        miListEmpresas.setText("Listar Empresas");
        jMenu2.add(miListEmpresas);

        miListEstagios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        miListEstagios.setText("Listar Estágios");
        jMenu2.add(miListEstagios);

        miListCursos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miListCursos.setText("Listar Cursos");
        jMenu2.add(miListCursos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Outros");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Creditos dos Programadores");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Sair");
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAlunoActionPerformed
        // TODO add your handling code here:
        JFRMCadastrarAluno cAluno = new JFRMCadastrarAluno();
        cAluno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadAlunoActionPerformed

    private void btnCadOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadOrientadorActionPerformed
        // TODO add your handling code here:
        JFRMCadastrarOrientador cOri = new JFRMCadastrarOrientador();
        cOri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadOrientadorActionPerformed

    private void btnListAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAlunosActionPerformed
        JFRMListarAlunos lAlu = new JFRMListarAlunos();
        lAlu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListAlunosActionPerformed

    private void btnListOrientadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListOrientadoresActionPerformed
        JFRMListarOrientadores lOri = new JFRMListarOrientadores();
        lOri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListOrientadoresActionPerformed

    private void btnListEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListEmpresasActionPerformed
        JFRMListarEmpresas lEmp = new JFRMListarEmpresas();
        lEmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListEmpresasActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        JFRMCreditos cred = new JFRMCreditos();
        cred.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btnCadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEmpresaActionPerformed
        // TODO add your handling code here:
        JFRMCadastrarEmpresa cEmp = new JFRMCadastrarEmpresa();
        cEmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadEmpresaActionPerformed

    private void btnCadEstagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadEstagioActionPerformed
        // TODO add your handling code here:
        JFRMCadastrarEstagio cadaEst = new JFRMCadastrarEstagio();
        cadaEst.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadEstagioActionPerformed

    private void btnCadCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCursosActionPerformed
        JFRMCadastrarCursos cCur = new JFRMCadastrarCursos();
        cCur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadCursosActionPerformed

    private void btnCadRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRepresentanteActionPerformed
        JFRMCadastrarRepresentanteLegal cRep = new JFRMCadastrarRepresentanteLegal();
        cRep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadRepresentanteActionPerformed

    private void btnListEstagiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListEstagiosActionPerformed
        JFRMListarEstagios lEst = new JFRMListarEstagios();
        lEst.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListEstagiosActionPerformed

    private void btnListCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCursosActionPerformed
        JFRMListarCursos lCur = new JFRMListarCursos();
        lCur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListCursosActionPerformed

    private void btnListRepresentantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListRepresentantesActionPerformed
        JFRMListarRepresentantes lRep = new JFRMListarRepresentantes();
        lRep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListRepresentantesActionPerformed

    private void miCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadAlunoActionPerformed
        JFRMCadastrarAluno cAluno = new JFRMCadastrarAluno();
        cAluno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miCadAlunoActionPerformed

    private void miCadOrientadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadOrientadorActionPerformed
        JFRMCadastrarOrientador cOri = new JFRMCadastrarOrientador();
        cOri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miCadOrientadorActionPerformed

    private void miCadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadEmpresaActionPerformed
        JFRMCadastrarEmpresa cEmp = new JFRMCadastrarEmpresa();
        cEmp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miCadEmpresaActionPerformed

    private void miCadEstagioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadEstagioActionPerformed
        JFRMCadastrarEstagio cadaEst = new JFRMCadastrarEstagio();
        cadaEst.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miCadEstagioActionPerformed

    private void miCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadCursoActionPerformed
       JFRMCadastrarCursos cCur = new JFRMCadastrarCursos();
        cCur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miCadCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRMPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRMPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRMPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRMPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRMPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAluno;
    private javax.swing.JButton btnCadCursos;
    private javax.swing.JButton btnCadEmpresa;
    private javax.swing.JButton btnCadEstagio;
    private javax.swing.JButton btnCadOrientador;
    private javax.swing.JButton btnCadRepresentante;
    private javax.swing.JButton btnListAlunos;
    private javax.swing.JButton btnListCursos;
    private javax.swing.JButton btnListEmpresas;
    private javax.swing.JButton btnListEstagios;
    private javax.swing.JButton btnListOrientadores;
    private javax.swing.JButton btnListRepresentantes;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblName16;
    private javax.swing.JLabel lblName17;
    private javax.swing.JLabel lblName18;
    private javax.swing.JLabel lblName19;
    private javax.swing.JLabel lblName20;
    private javax.swing.JLabel lblName21;
    private javax.swing.JLabel lblName22;
    private javax.swing.JLabel lblName23;
    private javax.swing.JLabel lblName24;
    private javax.swing.JMenuItem miCadAluno;
    private javax.swing.JMenuItem miCadCurso;
    private javax.swing.JMenuItem miCadEmpresa;
    private javax.swing.JMenuItem miCadEstagio;
    private javax.swing.JMenuItem miCadOrientador;
    private javax.swing.JMenuItem miListAlunos;
    private javax.swing.JMenuItem miListCursos;
    private javax.swing.JMenuItem miListEmpresas;
    private javax.swing.JMenuItem miListEstagios;
    private javax.swing.JMenuItem miListOrientadores;
    // End of variables declaration//GEN-END:variables
}
